import "server-only";
import {
  S3Client,
  PutObjectCommand,
  DeleteObjectCommand,
  GetObjectCommand,
  ListObjectsV2Command,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

// Accept both the canonical names and the project's existing Doppler names.
const accountId = process.env.R2_ACCOUNT_ID;
const accessKeyId = process.env.R2_ACCESS_KEY_ID || process.env.R2_ACCESS_KEY;
const secretAccessKey = process.env.R2_SECRET_ACCESS_KEY || process.env.R2_SECRET_KEY;
const bucket = process.env.R2_BUCKET_NAME;
// public base URL (r2.dev or a custom domain), no trailing slash
const publicBase = (process.env.R2_PUBLIC_DOMAIN || process.env.PUBLIC_R2_URL || "").replace(/\/$/, "");

/** Shared resolved R2 config (also used by the presign route). */
export const r2Config = { accountId, accessKeyId, secretAccessKey, bucket, publicBase };

export const r2Configured = !!(accountId && accessKeyId && secretAccessKey && bucket && publicBase);

let _client: S3Client | null = null;
function client() {
  if (!(accountId && accessKeyId && secretAccessKey)) throw new Error("R2 is not configured");
  if (!_client) {
    _client = new S3Client({
      region: "auto",
      endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
      credentials: { accessKeyId: accessKeyId!, secretAccessKey: secretAccessKey! },
    });
  }
  return _client;
}

export function publicUrl(key: string) {
  return `${publicBase}/${key}`;
}

export async function uploadObject(key: string, body: Buffer | Uint8Array, contentType: string) {
  await client().send(new PutObjectCommand({ Bucket: bucket!, Key: key, Body: body, ContentType: contentType }));
  return publicUrl(key);
}

export async function deleteObject(key: string) {
  await client().send(new DeleteObjectCommand({ Bucket: bucket!, Key: key }));
}

/** Derive the storage key from a previously returned public URL (for deletes). */
export function keyFromUrl(url: string): string | null {
  if (!publicBase || !url.startsWith(publicBase + "/")) return null;
  return url.slice(publicBase.length + 1);
}

/* ------------------------------------------------------------------------ *
 * PRIVATE bucket — client financial documents & deliverables.
 * No public domain, no public URLs, ever. Access is exclusively through
 * short-lived presigned URLs minted by ownership-checked routes.
 * ------------------------------------------------------------------------ */

const privateBucket = process.env.R2_PRIVATE_BUCKET;

export const r2PrivateConfigured = !!(accountId && accessKeyId && secretAccessKey && privateBucket);

/** Presigned PUT for a direct browser upload into the private bucket. */
export async function presignPrivatePut(
  key: string,
  contentType: string,
  expiresIn = 60
): Promise<string> {
  if (!r2PrivateConfigured) throw new Error("Private R2 bucket is not configured");
  return getSignedUrl(
    client(),
    new PutObjectCommand({ Bucket: privateBucket!, Key: key, ContentType: contentType }),
    { expiresIn }
  );
}

/** Presigned GET (forced download) from the private bucket. */
export async function presignPrivateGet(
  key: string,
  opts?: { downloadName?: string; expiresIn?: number }
): Promise<string> {
  if (!r2PrivateConfigured) throw new Error("Private R2 bucket is not configured");
  return getSignedUrl(
    client(),
    new GetObjectCommand({
      Bucket: privateBucket!,
      Key: key,
      ResponseContentDisposition: `attachment; filename="${(opts?.downloadName ?? "download").replace(/["\\]/g, "")}"`,
    }),
    { expiresIn: opts?.expiresIn ?? 60 }
  );
}

/** Read an object's bytes from the private bucket (server-side, e.g. AI relay). */
export async function getPrivateObject(key: string): Promise<Buffer> {
  if (!r2PrivateConfigured) throw new Error("Private R2 bucket is not configured");
  const res = await client().send(new GetObjectCommand({ Bucket: privateBucket!, Key: key }));
  const bytes = await res.Body!.transformToByteArray();
  return Buffer.from(bytes);
}

/** Upload server-generated bytes (e.g. AI Studio deliverables) privately. */
export async function uploadPrivateObject(
  key: string,
  body: Buffer | Uint8Array,
  contentType: string
): Promise<void> {
  if (!r2PrivateConfigured) throw new Error("Private R2 bucket is not configured");
  await client().send(
    new PutObjectCommand({ Bucket: privateBucket!, Key: key, Body: body, ContentType: contentType })
  );
}

export async function deletePrivateObject(key: string): Promise<void> {
  if (!r2PrivateConfigured) throw new Error("Private R2 bucket is not configured");
  await client().send(new DeleteObjectCommand({ Bucket: privateBucket!, Key: key }));
}

export type PrivateObject = { key: string; size: number; lastModified: string | null };

/** List objects under a prefix in the private bucket (e.g. "backups/"). */
export async function listPrivateObjects(prefix: string, maxKeys = 1000): Promise<PrivateObject[]> {
  if (!r2PrivateConfigured) return [];
  const res = await client().send(
    new ListObjectsV2Command({ Bucket: privateBucket!, Prefix: prefix, MaxKeys: maxKeys })
  );
  return (res.Contents ?? [])
    .filter((o) => o.Key)
    .map((o) => ({
      key: o.Key!,
      size: o.Size ?? 0,
      lastModified: o.LastModified ? o.LastModified.toISOString() : null,
    }));
}
